import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/modules/Shared/Footer";
import Navbar from "@/components/modules/Shared/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Doctor Patient Management",
  description: "Generated by create Md Touhidur Zaman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-white fixed min-w-dvw">
          <Navbar/>
        </div>
        <div className="min-h-dvh pt-16 md:pt-28">
          {children}
        </div>
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
